#!/usr/bin/env python3

import base64

def decypher(encoded):
    """Decypher the string in parameter."""

    result = []
    for coord_i in xrange(len(encoded)):
        coord_j = ord(encoded[coord_i])
        if coord_j >= 33 and coord_j <= 126:
            result.append(chr(33 + ((coord_j + 14) % 94)))
        else:
            result.append(encoded[coord_i])
    return ''.join(result)

password = 'test'
encrypted = base64.b64encode(decypher(base64.b64encode(password)))
decrypted = base64.b64decode(decypher(base64.b64decode(password)))
print 'encryped password: ' + encrypted
print 'decryped password: ' + decrypted
